### ISSUE TITLE
Add Owner Data Column

### ISSUE THREAD

**Issue by Redth** [cake-contrib/Cake.AddinDiscoverer#10]
Would be nice to see in the table for each addin, who the nuget owner(s) is/are.

I'd like to be able to skim through the list and see all of my addins to see where they are at.

**Comment by Jericho** [comment]
Unfortunately, nuget.org omits the owner information when we fetch metadata about an addin. This is a known issue which I [reported](https://github.com/NuGet/Home/issues/6679) and a [feature request](https://github.com/NuGet/NuGetGallery/issues/5647) was created for it.

In fact, this issue is [preventing](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/9) me from auditing if cake-contrib has been aded as co-owner of a given addin.

**Comment by gep13** [comment]
@Jericho great work on getting the feature request added with NuGet.  This would be great to get added to the Addin Discover.  Obviously, we could go further and parse the HTML of the package page to find the information, but that isn't an ideal solution.  Are you currently downloading/inspecting the nupkg of each addin, or are you relying on the package metadata solely?

**Comment by Jericho** [comment]
@gep13 I am querying the metadata.

**Comment by Jericho** [comment]
@Redth @gep13 since we can't get the nuget owner, I would like to propose a compromise: how about we display the maintainer/author?

The maintainer comes from the Status.md file in the cake-contrib repo. Here's an example:
![image](https://user-images.githubusercontent.com/112710/39648643-e0bb2f5e-4fb0-11e8-9c5b-30853fb0e3c4.png)

And the author comes from the `yml` file for each addin in the cake-build repo. Here's an example:
![image](https://user-images.githubusercontent.com/112710/39648698-1868d3ca-4fb1-11e8-9064-d55ee6505272.png)

If you think this is an acceptable compromise, I would like to discuss what you think we should in cases where the two values don't match. For instance, in the screenshots I included above you'll notice the maintainer for Cake.Android.Adb is `redth` and the author in the yml file is `Jonathan Dick`. Which one do we think is more likely to be accurate?

**Comment by AdmiringWorm** [comment]
I think adding the maintainer/author should be enough IMO.

I also think that the Author in the yml file should probably override the maintainer from the `Status.md` file.
I would think that most likely the yml file was provided by the maintainer, and as such it should be made a priority.

Just my 2 cents.

**Comment by gep13** [comment]
The Maintainer column is going to be subject to human error, i.e. on my part, so it isn't perfect, but it is better than nothing.

Personally, I would prefer to see the person's github name, i.e. `redth` in your example, as that is then linkable through to somewhere, like their GitHub profile.  I agree with what @AdmiringWorm is saying though, in terms of them submitting the yml file, therefore that should be regarded as the source of truth.  Perhaps what we need to do is to add another property to those yml files which is the person's GitHub user name?

**Comment by Redth** [comment]
Yup maintainer would be great!  I'd prefer seeing the GitHub name also.

**Comment by Jericho** [comment]
Ok I think we all agree that the maintainer in Status.md should be a fallback value in case no author information was provided in the yml or yml is missing.

But it means that we are at the mercy of the information provided by the maintainer himself. We can't force them to provide their github name (unless, as @gep13 suggested, we add a new field in the yml file for this info).

**Comment by AdmiringWorm** [comment]
👍 for adding a new field for github usernames

**Comment by Jericho** [comment]
Ok, here's what I intend to do.

- Add a column in the generated markdown and in the Excel file titled `Author`
- The data comes from the following, in order of preference:
    1. A field called `Author github username` in the yml file (do you guys agree with the name of this new field?)
    2. The `Author` field in the yml file
    3. The maintainer field in the Status.md file

**Comment by gep13** [comment]
@Jericho so that we don't run into problems with spaces, etc, let's call it `AuthorGitHubUserName`.  I will speak to the team about getting it added.

Would it make sense for the rendered output to look something like this:

Gary Ewan Park ([@gep13](https://github.com/gep13))

When the Author and GitHub UserName are both present, and are different?

**Comment by AdmiringWorm** [comment]
why not just `GitHubUser`, is it really necessary to have a longer name than that?

**Comment by Jericho** [comment]
@gep13 my concern with the `author's-name-which-can-be-quite-long (@githubname)` format is that is can make the column pretty wide and we have limited real estate. This would force people to scroll left and right to view the table in the resulting `Audit.md`. I don't have the same concern in the Excel file since is easy for people to resize and/or hide a given column.

**Comment by Jericho** [comment]
@gep13 agree with your comment regarding spaces in the yaml field name. Therefore I willl look for a field called `AuthorGitHubUserName`.

**Comment by Jericho** [comment]
Here's a draft of what the markdown will look like when the [new column is added](https://github.com/Jericho/Home/blob/patch-4/Audit.md).

As you can see, the table is too wide and the right side is cut-off. You have to scroll all the way down in order to see the horizontal scroll bar. I don't like this at all!

What do you guys think if I omit the Author column from the markdown and add a link to the Excel file that says something along the lines of "click here to view an Excel spreadsheet containing the audit result along with some additional data that we couldn't fit on this web page"?

**Comment by Jericho** [comment]
Here's another draft where I included the `Maintainer` column and removed the last two columns on the far right (which would be transfered to the Excel report). As you can see, the right-most column (which is now the `Framework` column) is cut-off.

**Comment by Jericho** [comment]
Ok, here's what I ended up doing:

The Maintainer, Icon, Yaml, and 'Transferred to cake-contrib' columns are displayed in the Excel report only and the markdown file has a link to download the Excel file.

**Comment by gep13** [comment]
@Jericho great work! :+1:
