### ISSUE TITLE
Do not link to addin repo if it does not exist

### ISSUE THREAD

**Issue by gitfool** [cake-contrib/Cake.AddinDiscoverer#102]
Discovered while traversing all the GitHub repos in [Audit for Cake](https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.33.0.md), some of the repos have packages on NuGet but no longer exist on GitHub, currently:
* [Cake.ArtifactDrop](https://github.com/stefandevo/Cake.ArtifactDrop)
* [Cake.OssIndex](https://github.com/TrekkingForCharity/Cake.OssIndex)

The repo link should be validated and if not found an addin should be listed _without_ the link.

**Comment by Jericho** [comment]
I like your suggestion. 

I just did a quick test and here are some preliminary results:
- I found only 2 invalid URLs (presumably the URLs for the two nuget packages you mentioned) 
- I was able to validate 119 URLs
- I triggered GitHub's abuse detection which prevented me from checking 186 URLs

![image](https://user-images.githubusercontent.com/112710/81363876-56057c80-90b2-11ea-8176-ec353b0503cf.png)

So, I will need to figure out a way to slow down the process enough that I don't trigger the abuse detection and avoid the `HTTP 429 TooManyRequests` responses,

**Comment by gitfool** [comment]
While testing some changes for [dependabot-core](https://github.com/dependabot/dependabot-core), we found using a GITHUB PAT avoids the `429`s.

**Comment by Jericho** [comment]
In this case I can't rely on the GITHUB API because not all projects are hosted on GITHUB so I simply issue a `HTTP HEAD` request to the project URL found in the package and inspect the response. 

I was able to add a delay when I get a `429`. The duration of the delay is based on the value in the `Retry-After` header in the response (which seems to always be 60 seconds). This allows me to complete checking all URLs but it also means that it takes a little over 2 minutes to complete this step.

```
NotFound	5
OK	302
```

So we are adding 2 minutes to generate the report to correct only 5 invalid URLs. I'm not sure I think it's worth it...

**Comment by gitfool** [comment]
If you're not already using it, I'd recommend using [Polly](https://github.com/App-vNext/Polly) for easy backoff and retry policies.

It depends on how often you generate the report though, right? An extra 2 minutes is nothing if run once an hour, let alone once a day or more.
