### ISSUE TITLE
Reconsider ".git missing" warning

### ISSUE THREAD

**Issue by gitfool** [cake-contrib/Cake.AddinDiscoverer#104]
I noticed that [audit for recipes](https://github.com/cake-contrib/Home/blob/master/Audit_for_recipes.md) shows a ".git missing" warning for [Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon), [Cake.Recipe](https://github.com/cake-contrib/Cake.Recipe) and [Cake.Tool](https://github.com/cake-build/cake). This seems to be coming from [Constants.REPORT_COLUMNS](https://github.com/cake-contrib/Cake.AddinDiscoverer/blob/develop/Source/Cake.AddinDiscoverer/Utilities/Constants.cs#L229-L237).

I'm not sure why this is checked, but there's nothing I can do about it for `Cake.Dungeon` since it uses [Source Link](https://github.com/dotnet/sourcelink) with [PublishRepositoryUrl](https://github.com/gitfool/Cake.Dungeon/blob/master/Directory.Build.props#L19). Given how common it is to use Source Link now, please consider removing this check.

**Comment by Jericho** [comment]
Are you saying that setting `PublishRepositoryUrl` to `true` adds the repo url but without `.git`? That's weird because I publish all my own libraries that way and they do have the `.git` extension. For instance check out my StrongGrid project:
- here's the [.csproj](https://github.com/Jericho/StrongGrid/blob/develop/Source/StrongGrid/StrongGrid.csproj#L13)
- and you can check out the package metadata on [Nuget.org](https://www.nuget.org/packages/StrongGrid/) (notice the "source Repository" link includes `.git`)

One difference I noticed is that you included the `PublishRepositoryUrl` setting in `.build.props` file while I have it in my `.csproj`. I don't know if it makes a difference or not, but it's a difference I noticed.

Besides, @gep13 [sought and received confirmation](https://twitter.com/adgrv/status/1127591787697061888?s=21) that the repo url should indeed include `.git` extension.

**Comment by gitfool** [comment]
> Are you saying that setting PublishRepositoryUrl to true adds the repo url but without .git?

Yes.

Here's [Cake.Dungeon](https://www.nuget.org/packages/Cake.Dungeon/) on [nuget.org](https://www.nuget.org/).

Here's the extracted `Cake.Dungeon.nuspec` after downloading from NuGet:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Cake.Dungeon</id>
    <version>4.4.0</version>
    <authors>Sean Fausett</authors>
    <owners>Sean Fausett</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <icon>icon.png</icon>
    <projectUrl>https://github.com/gitfool/Cake.Dungeon</projectUrl>
    <description>A playground for Cake build scripts.</description>
    <copyright>Copyright © 2020</copyright>
    <tags>Cake Build Scripts</tags>
    <repository type="git" url="https://github.com/gitfool/Cake.Dungeon" commit="b4f04eed3f9c66665d62367101c7c0cabc221e5c" />
  </metadata>
</package>
```

**Comment by Jericho** [comment]
I believe you. And I see it also [here](https://www.nuget.org/packages/Cake.Dungeon/). But why is it working as expected with my libraries but not in your libraries???? I have no idea. I just pointed out a difference in how your project is structured compared to mine. Maybe that's something for you to investigate?

**Comment by gitfool** [comment]
I downloaded the source to [StrongGrid](https://github.com/Jericho/StrongGrid) and tried the following:
* Strip target frameworks to `netstandard2.0` only
* Add `Directory.Build.props`
* Remove symbols package generation (use embedded PDB)

Clean build each time always links to `https://github.com/Jericho/StrongGrid.git`. No idea. 🤔

**Comment by Jericho** [comment]
Strange...

But the bottom line is that checking for the presence of the `.git` extension is the right thing to do as far as the audit tool is concerned.

**Comment by gitfool** [comment]
Why's that? What's it checking exactly?

**Comment by Jericho** [comment]
As I mentioned earlier, @gep13 received confirmation that this URL should have the .git extension. Also, check out discussion in #44 and more specifically @AdmiringWorm's [comment](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/44#issuecomment-491386624).

**Comment by gitfool** [comment]
I don't think it's that simple, and actually I've found out one way, maybe _the_ way, to replicate it. I can build `StrongGrid` without changing anything and get a url _without_ the `.git` extension. I just have to clone its repo without that extension.

So I think that Source Link is just using the remote details, which depends on how the repo is cloned / initialized, which depends on the build server. You're using AppVeyor; I'm using Azure Pipelines, GitHub Actions and GitLab CI, where Azure Pipelines is currently responsible for publishing to NuGet.

* AppVeyor initializes the git repo [here](https://ci.appveyor.com/project/Jericho/stronggrid/builds/32767085#L3) (`StrongGrid`)
* Azure Pipelines initializes the git repo [here](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=540&view=logs&j=1c8ce01e-97de-5be9-a863-648419f09741&t=da0ec0f8-43e2-5c19-fb5c-4c50d5eddf90&l=16) (`Cake.Dungeon`)
* GitHub Actions initializes the git repo [here](https://github.com/gitfool/Cake.Dungeon/runs/658393642?check_suite_focus=true#step:3:28) (`Cake.Dungeon`)
* GitLab CI initializes the git repo [here](https://gitlab.com/gitfool/Cake.Dungeon/-/jobs/545151860#L16) (`Cake.Dungeon`)

**Comment by gitfool** [comment]
@Jericho Please accept my apologies if I came across poorly and have annoyed you. I'm just trying to understand and help improve things.

Could you please give me the courtesy of a followup to my findings above, which IMHO show that the assumptions made by this warning are flawed and does not align with real world implementations.

**Comment by gep13** [comment]
@gitfool just to add my two cents to this issue...

We had a conversation with the NuGet team about ensuring that the best practices for NuGet packaging is being followed.  This includes things like:

* using license expression, rather than license URL
* using embedded icon, rather than URL
* including a RepositoryUrl
* etc

All of these things are "expected" to be contained within the nupkg metadata.  

To follow up with this, it was confirmed by the PM of the NuGet Team that the RepositoryUrl "should" include the .git extension.  If we can confirm that this guidance has changed, then we will adjust the Audit to for account for this, but to the best of our knowledge, the .git extension is expected to be included.

**Comment by gitfool** [comment]
@gep13 understood, thanks!

It clearly doesn't help if common tooling like Source Link doesn't follow these guidelines though, and will mean repos like mine will get flagged through no fault of their own. 😞

**Comment by Jericho** [comment]
@gitfool I mentioned before that the extension is supposed to be present which is why the audit tool checks for it's presence but please take note that it records a warning (as opposed to a failure) when the extension is missing due to the fact that it probably works even if the extension is missing.

I think you have already proven that some tooling, combined with some CI environment are able to work perfectly fine without the expected extension but I continue to maintain that the extension is indeed expected (albeit not required, as you have proven) and therefore our audit tool should continue to check for it.

Let me know if you feel like I misunderstood the result of your testing.

**Comment by gitfool** [comment]
@Jericho all good. (I always treat warnings as errors, so would've preferred to fix them if possible.)
