### ISSUE TITLE
Don't create PR's if a new pre-release version of an existing package is released

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#116]
Currently addin discoverer creates PRs to the https://github.com/cake-build/website/ repo if metadata of an addin changes. This includes `Prerelease` metadata. 

IMHO we should only use non-prerelease versions of addins for documentation on cakebuild.net. The current behavior creates quite some noise for certain addins which have regular pre-release versions, followed by stable versions (e.g. `Cake.Issues.*`, `Cake.GitVersioning`).

If common understanding is that pre-release versions of addins should also be listed on cakebuild.net, we should do this only for addins which don't have a stable release yet. If a pre-release version for an addin is released for an addin which already has a stable release, we should not update `prerelease` metadata and still document latest stable version of the addin.

**Comment by Jericho** [comment]
I brought this up in June last year but I don't know that a consensus emerged from the [discussion](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/52#issuecomment-498763563). As far as I know, this flag is needed in order to generate the documentation. @daveaglick [wondered](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/52#issuecomment-522379258) whether this flag is needed anymore and @devlead confirmed that a change would need to made in order to fetch latest version of a package regardless of the prerelease flag. I don't think this change has ben made and therefore, as far as I know, we still need to track the prerelease flag.

**Comment by pascalberger** [comment]
I created a PR to remove prerelease flag completely since it currently doesn't do anything: https://github.com/cake-build/website/pull/1159
