### ISSUE TITLE
Automated audit incorrect

### ISSUE THREAD

**Issue by ejball** [cake-contrib/Cake.AddinDiscoverer#19]
Items 3 and 4 of a [recent automated audit](https://github.com/ejball/XmlDocMarkdown/issues/31) are incorrect.

The [Cake addin project](https://github.com/ejball/XmlDocMarkdown/blob/master/src/Cake.XmlDocMarkdown/Cake.XmlDocMarkdown.csproj) target framework and package icon are correct.

**Comment by Jericho** [comment]
Regarding item 4: you are using the following URL:
```
https://raw.githubusercontent.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png
```

but the audit tool is looking for:
```
https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png
```

That explains why the audit tool indicates that your addin is not using the recommended URL.

I continue investigating item 3...

**Comment by Jericho** [comment]
Regarding item 3:

your solution references the following 6 projects: 
- XmlDocMarkdown.Core
- XmlDocMarkdown
- ExampleAssembly
- XmlDocMarkdown.Tests
- Cake.XmlDocMarkdown
- XmlDocTarget

The audit tool ignores "test" projects which leaves 5 project. Since there is no way (that I'm aware of) for the audit tool to determine which of these 5 projects contains the source for your addin it ends up looking at all 5 projects and these 5 projects collectively target `netstandard2.0`, `netstandard1.1` and `net47`. That explains why the audit tools complains that you are not targeting the expected framework.

**Comment by gep13** [comment]
>@Jericho said...
That explains why the audit tool indicates that your addin is not using the recommended URL

Usage of the cdn.rawgit.com URL is recommended as it serves the files using correct content headers, and also from a global CDN.  The URL that you have isn't taking advantage of that.
