### ISSUE TITLE
IsPreRelease discussion

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#58]
Currently, an addin is deemed to be 'prerelease' if it's explicitly marked as such in the nuspec **OR** it references another nuget package that is marked as prerelease. 

The reason for this logic is because Wyam will no properly generate an addin's documentation if we don't mark it as prerelease in the YAML file we generate.

However, as @AdmiringWorm recently [pointed out](https://github.com/cake-contrib/Cake.Recipe/pull/376#issuecomment-512007293), this logic causes addins such as Cake.Graph to be excluded from the "Update Cake.Recipe" logic because they reference a prerelease package. 

I would like to open the discussion: is this the desired behavior?

As far as updating Cake.Recipe, we probably want to exclude package that are explicitly marked as prerelease, but we probably don't want to exclude packages that are deemed prereleased because the reference another package which happens to be prerelease.

@gep13 can you chime in this discussion?

**Comment by AdmiringWorm** [comment]
In my opinion, I don't think it is correct to exclude a addin just because it references a pre-release package.

I am not sure if excluding pre-release packages is correct at all.
If we take this with a little grain of salt, excluding pre-release packages effectively means to exclude unstable releases.
Now, if we are thinking in the path of Semver 2.0, then that means that any release that is in the range of `0.x` should also be excluded (after all, all software that have not yet hit the 1.0 release should in theory be thought of unstable releases, or not entirely production ready).

However, in the context of Cake.Recipe. It would make sense to exclude releases of an addin marked as a pre-release, but IMO not just because they reference a package using a pre-release tag.

**Comment by Jericho** [comment]
I'm in agreement that only package specifically marked as prerelease should be excluded from Cake.Recipe but the current logic must remain in place as far as YAML files generation is concerned.

**Comment by Jericho** [comment]
3.21.0 has been released and Cake.Graph is now properly considered compatible with Cake 0.33.0
