### ISSUE TITLE
Cake.Warp is detected as not using Cake.Recipe

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.AddinDiscoverer#65]
The Cake.Warp addin is detected as not using Cake.Recipe, this is incorrect as it do indeed use Cake.Recipe (version 1.0.0).

I think the reason why it perhaps is detected as not using it may be because I extend/override some of the tasks already in Cake.Recipe to fit my own needs.

The main build file is the following:
https://github.com/cake-contrib/Cake.Warp/blob/develop/recipe.cake

Which loads in additional files as well loading Cake.Recipe.

**Comment by Jericho** [comment]
Thanks for letting me know. The issue is that there are multiple cake files in this repo and none follow the "usual" naming convention (which is `setup.cake` or `build.cake`). In this scenario, the automated process ends up parsing a random cake file from the repo.

I'll improve the process to be able to handle such scenario.

**Comment by AdmiringWorm** [comment]
> The issue is that there are multiple cake files in this repo and none follow the "usual" naming convention

I will blame @gep13 for this. He wanted me to use `recipe.cake` as the name of the base file :smile:.
See what problems you cause Gary :laughing: 

Should the discover really depend on the naming of the file? Wouldn't it be better to scan all `.cake` files, and stop parsing if a match is found (starting with the files in the repository root)?

**Comment by gep13** [comment]
>@AdmiringWorm said...
I will blame @gep13 for this. He wanted me to use recipe.cake as the name of the base file 😄.
See what problems you cause Gary 😆

Ha ha!

I have started using `recipe.cake` for all addin repositories which are using Cake.Recipe.  This gives a visual queue that it is being used, without drilling into it.  It is a convention, but now a rule.  If you could add `recipe.cake` into the standard list of files to check, that would be great.

Sorry to cause problems!

**Comment by gep13** [comment]
>@AdmiringWorm said...
Should the discover really depend on the naming of the file? Wouldn't it be better to scan all .cake files, and stop parsing if a match is found (starting with the files in the repository root)?

I think the issue here is the number of calls required to GitHub to get all the information required.

**Comment by AdmiringWorm** [comment]
> I think the issue here is the number of calls required to GitHub to get all the information required.

Fair enough, I didn't actually think about that.

**Comment by Jericho** [comment]
@AdmiringWorm Indeed I shouldn't rely on addin authors following a naming convention. As @gep13 said, my objective was to limit the number of API calls because I was triggering github's abuse detection when scanning all 300+ repos for all cake file. However, I now have a much better approach that allows me to loop through files in a repo without invoking github's API excessively so I will be able to improve the logic and handle all cake files.

**Comment by Jericho** [comment]
New version published. The report was refreshed and Cake.Warp is not properly detected as using Cake.Recipe 1.0.0

**Comment by AdmiringWorm** [comment]
Awesome, thanks @Jericho
