### ISSUE TITLE
Standardize URL format in generated YAML files

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#71]
In order to ensure URLs in YAML files generated by the AddinDiscoverer are consistent, we decided to standardize on trimming the slash at the end like the following example:
`https://github.com/agc93/Cake.AutoRest` as opposed to `https://github.com/agc93/Cake.AutoRest/`

This was discused in #52

**Comment by agc93** [comment]
This is always a hot topic. For trailing slashes, there's two things worth noting: 

1. We should definitely normalise these since consistency is king for this sort of thing
2. Are we expecting these URLs to be machine readable? If so, trailing slash is crucial.

The biggest case is that if a **strict** (i.e. stuck to the letter of the specifications) created a relative link to `issues` from `https://github.com/agc93/Cake.AutoRest` it would actually result in `https://github.com/agc93/issues` which is obviously wrong.

Given GitHub supports both formats, my *personal* preference is to follow the specs and add the trailing slash to make relative URLs relative to that project rather than the org.

**Comment by gep13** [comment]
Hmm, based on this argument, I would be hard pushed to argue against it.

**Comment by Jericho** [comment]
As far as the AddinDiscoverer is concerned, this url is simply written in the YAML file and Wyam parses this file to generates documentation. I have no idea if Wyam creates relative links as @agc93 describes though.

We should just be safe and add the trailing slash.

**Comment by Jericho** [comment]
FYI: this logic will cause AddinDiscoverer to update about 75 or so yaml files because they contain a URL that is not formatted as we agreed.

I just want to make sure we are all aware.

**Comment by gep13** [comment]
Yip, understood. Will this be a single PR, or using the new single addin per PR functionality I saw you testing out?

**Comment by Jericho** [comment]
I will be a single PR if #670 is closed before I publish the next version of AddinDiscoverer. It will be 75 individual issues+PRs if I publish the next version (whether #670 is closed or not).

**Comment by gep13** [comment]
Ok, I am just away to close #670 once the CI build passes, so perhaps best to get a single PR in with all those changes.
